name: Firecracker
  main: thebigsmileXD\Firecracker\Main
  version: 0.1.0
  api: 1.0.0
  load: Test
  authors: [jiang]
  prefix: "throw me :)"
  commands:
   firecracker:
    description: "Commands for Firecracker"
    usage: "/firecracker get"
    permission: firecracker.command
    aliases: [fc]
  permissions:
    firecracker.command:
      description: Permission for /firecracker commands.
      default: true
